services:
  db:
    image: "postgres:17"
    healthcheck:
      test: [ 
        "CMD-SHELL", 
        "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME?:DATABASE_USERNAME not set}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD?:DATABASE_PASSWORD not set}"
      POSTGRES_DB: "${DATABASE_NAME?:DATABASE_NAME not set in env}"
    volumes:
      - ./db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1gb
  django:
    build: ./app
    restart: always
    environment:
      SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/static
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          memory: 256mb
  caddy:
    image: "caddy:latest"
    restart: always
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config
      - ./static:/static
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django